/**
 * AUTO-GENERATED by `make feature` — do not edit manually.
 * Merged into sidebar menu items in useSidebar.tsx.
 */
import type { NavMenuItem } from '@/components/NavMenu';

export function buildGeneratedFeatureMenuItems(_t: (key: string) => string): NavMenuItem[] {
  return [];
}
